### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by prabhat7k** [prabhat7k/Hactoberfest22#2]

**Comment by anuragK-24** [comment]
i wanted to do this task, can u assign it to me?

**Comment by tpt7k** [comment]
can i get this?

**Comment by prabhat7k** [comment]
Since, @hfr58gb has asked first I'm assigning this to him. If he fails then I'll assign to you @tpt7k

**Comment by anuragK-24** [comment]
Done assigned task, checkout the [PR](https://github.com/prabhat7k/Hactoberfest22/pull/8)

**Comment by anuragK-24** [comment]
Thanks @prabhat7k

**Comment by prabhat7k** [comment]
> Done assigned task, checkout the [PR](https://github.com/prabhat7k/Hactoberfest22/pull/8)

next time mention the issue number in the PR comment, it will automatically close the issue.
Thanks for contributing @hfr58gb
